version: "3.4"

services:
  googleddnsupdater:
    build: .
    container_name: "googleddnsupdater"
    environment:
      - DdnsSettings__Hosts__0__Endpoint=${HOST_NAME}
      - DdnsSettings__Hosts__0__User=${USER}
      - DdnsSettings__Hosts__0__Password=${PASSWORD}
      - DdnsSettings__Hosts__0__OverrideIp=${OVERRIDE_IP}
      - DdnsSettings__UpdateInterval=${UPDATE_INTERVAL}
      - DdnsSettings__MaxParallelExecutions=${MAX_PARALLEL_EXECUTIONS}
    ports:
      - "5400:5400"